# Generated by Django 2.1 on 2018-08-20 18:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyMorning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_status', models.CharField(choices=[('AP', 'Approved'), ('DC', 'Declined'), ('PD', 'Pending')], default='PD', max_length=2)),
                ('reason', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('date_applied_for', models.DateField(default=datetime.datetime(2018, 8, 20, 18, 33, 10, 699872, tzinfo=utc))),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
            ],
        ),
        migrations.CreateModel(
            name='LateNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_status', models.CharField(choices=[('AP', 'Approved'), ('DC', 'Declined'), ('PD', 'Pending')], default='PD', max_length=2)),
                ('reason', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('date_applied_for', models.DateField(default=datetime.datetime(2018, 8, 20, 18, 33, 10, 698872, tzinfo=utc))),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
            ],
        ),
        migrations.CreateModel(
            name='OverNight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_status', models.CharField(choices=[('AP', 'Approved'), ('DC', 'Declined'), ('PD', 'Pending')], default='PD', max_length=2)),
                ('reason', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('departure', models.DateField(default=datetime.datetime(2018, 8, 20, 18, 33, 10, 700872, tzinfo=utc))),
                ('arrival', models.DateTimeField(default=datetime.datetime(2018, 8, 21, 18, 33, 10, 700872, tzinfo=utc))),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date submitted')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('l_name', models.CharField(max_length=50)),
                ('room_n', models.IntegerField()),
                ('form_n', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='overnight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.User'),
        ),
        migrations.AddField(
            model_name='latenight',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.User'),
        ),
        migrations.AddField(
            model_name='earlymorning',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.User'),
        ),
    ]
