# Generated by Django 2.1 on 2018-08-20 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlymorning',
            name='date_applied_for',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 18, 34, 27, 486264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='latenight',
            name='date_applied_for',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 18, 34, 27, 484264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='overnight',
            name='arrival',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 21, 18, 34, 27, 487264, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='overnight',
            name='departure',
            field=models.DateField(default=datetime.datetime(2018, 8, 20, 18, 34, 27, 487264, tzinfo=utc)),
        ),
    ]
